version: "3"
services:
  prometheus:
    image: prom/prometheus:latest
    volumes: 
        - ./monitoring/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'        
    ports:
      - 9090:9090
    restart: always

  grafana:
    image: grafana/grafana
    user: "104"
    depends_on:
      - prometheus
    ports:
      - 3333:3000
    volumes:
      - ./grafana-config/service-metrics-datasource.yml:/etc/grafana/provisioning/datasources/service-metrics-datasource.yml
      - ./grafana-config/service-metrics-dashboard.yml:/etc/grafana/provisioning/dashboards/service-metrics-dashboard.yml
      - ./grafana-config/Gateway-Service-Metrics-Dashboard.json:/var/lib/grafana/dashboards/Gateway-Service-Metrics-Dashboard.json
    env_file:
      - ./monitoring/grafana/config.monitoring
    restart: always    

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"

  fake_api:
    image: jaxgeller/lwan
    volumes:
      - ./data:/lwan/wwwroot
    ports:
      - "8000:8080"

      
  kraken_designer:
    image: devopsfaith/krakendesigner:latest
    ports:
      - "8787:80"
  
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=krakend
      - INFLUXDB_USER=admin
      - INFLUXDB_USER_PASSWORD=admin
      - INFLUXDB_ADMIN_USER=sa
      - INFLUXDB_ADMIN_PASSWORD=sapwd

  krakend_ce:
    image: devopsfaith/krakend:1.1.1
    volumes:
      - ./api-gw:/etc/krakend
    ports:
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"      
    depends_on:
      - fake_api
      - jaeger
      - prometheus
      - influxdb
      - graylog

  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: mongo:3
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    ports:
      - 9200:9200
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/security-settings.html#general-security-settings
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:2.4.0-1
    environment:
      # CHANGE ME!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp